# Generated by Django 4.2.10 on 2024-02-15 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='name',
            new_name='title',
        ),
    ]
