# Generated by Django 4.2.10 on 2024-02-15 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_eventtype_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventtype',
            unique_together={('title', 'user')},
        ),
    ]
