# Generated by Django 4.2.10 on 2024-02-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_options_event_created_event_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(default='#1975d2', max_length=10),
        ),
    ]
